[package]
name = "application"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
thiserror = "1.0.63"
rand = "0.8.5"
tokio = "1.39.3"
log = "0.4.22"
async-trait = "0.1.81"