[package]
name = "persistence"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.1", features = ["postgres", "runtime-tokio", "chrono"] }
tokio = { version = "1.39.3", features = ["full"] }
domain = { path = "../domain" }
lettre = "0.11.7"
async-trait = "0.1.81"