[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37", features = ["full"] }
chrono = "0.4.38"
sqlx = "0.8.1"
thiserror = "1.0.63"
rand = "0.8.5"
async-trait = "0.1.81"
serde = { version = "1.0.209", features = ["derive"] }

[features]
models = []