name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --release

      - name: Upload Binaries
        uses: actions/upload-artifact@v3
        with:
          name: Avatars binaries
          path: |
            target/release/avatars

  test_main:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Download Binaries
        uses: actions/download-artifact@v3
        with:
          name: Avatars binaries

      - name: Run build for main
        run: cargo build --release

      - name: Run tests for main
        run: cargo test --release

  test_domain:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Download Binaries
        uses: actions/download-artifact@v3
        with:
          name: Avatars binaries

      - name: Run build for domain
        run: cargo build --manifest-path domain/Cargo.toml --release

      - name: Run tests for domain
        run: cargo test --manifest-path domain/Cargo.toml --release

  test_application:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Download Binaries
        uses: actions/download-artifact@v3
        with:
          name: Avatars binaries

      - name: Run build for application
        run: cargo build --manifest-path application/Cargo.toml --release

      - name: Run tests for application
        run: cargo test --manifest-path application/Cargo.toml --release

  test_persistence:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Download Binaries
        uses: actions/download-artifact@v3
        with:
          name: Avatars binaries

      - name: Run build for persistence
        run: cargo build --manifest-path persistence/Cargo.toml --release

      - name: Run tests for persistence
        run: cargo test --manifest-path persistence/Cargo.toml --release