[package]
name = "web"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37", features = ["full"] }
askama = "0.12.1"
axum = "0.7.5"
askama_axum = "0.4.0"
application = { path = "../application" }
tower-http = { version = "0.5.2", features = ["full"] }
